language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - jruby-9.0.5.0
  - ruby-head

sudo: false
cache:
  - bundler

env:
  - COVERALL=1

notifications:
  recipients:
    - weppos@weppos.net

matrix:
  include:
  - rvm: 2.0
    gemfile: Gemfile-2
  - rvm: 2.1
    gemfile: Gemfile-2
  - rvm: 2.2
    gemfile: Gemfile-2
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.0.5.0
