language: ruby

sudo: false
cache:
  - bundler

env:
  - COVERALL=1

notifications:
  email:
    - weppos@weppos.net

gemfile:
  - Gemfile.activesupport-4.x

rvm:
  - 2.0
  - 2.1
  - 2.2
  - jruby-9.0.5.0
  - ruby-head

matrix:
  include:
    - rvm: jruby-9.0.5.0
      gemfile: Gemfile
    - rvm: ruby-head
      gemfile: Gemfile
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.0.5.0
