language: ruby

sudo: false
cache:
  - bundler

notifications:
  recipients:
    - weppos@weppos.net

matrix:
  include:
    - rvm: 2.0
      gemfile: Gemfile.activesupport-4.x
      env: COVERALL=0
    - rvm: 2.1
      gemfile: Gemfile.activesupport-4.x
      env: COVERALL=0
    - rvm: 2.2
      gemfile: Gemfile.activesupport-4.x
      env: COVERALL=0
    - rvm: 2.2
      gemfile: Gemfile
      env: COVERALL=1
    - rvm: jruby-9.0.5.0
      gemfile: Gemfile
      env: COVERALL=0
    - rvm: jruby-9.0.5.0
      gemfile: Gemfile.activesupport-4.x
      env: COVERALL=0
    - rvm: ruby-head
      gemfile: Gemfile.activesupport-4.x
      env: COVERALL=0
    - rvm: ruby-head
      gemfile: Gemfile
      env: COVERALL=0
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.0.5.0
